export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT = 'LOGOUT';
export const ADD_TWEET = 'ADD_TWEET';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_SUCCEEDED = 'GET_PROFILE_DATA_SUCCEEDED';
export const GET_PROFILE_DATA_FAILED = 'GET_PROFILE_DATA_FAILED';
export const CHANGE_PROFILE_DATA = 'CHANGE_PROFILE_DATA';