export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT = 'LOGOUT';
export const ADD_TWEET = 'ADD_TWEET';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_SUCCEEDED = 'GET_PROFILE_DATA_SUCCEEDED';
export const GET_PROFILE_DATA_FAILED = 'GET_PROFILE_DATA_FAILED';
export const CHANGE_PROFILE_DATA = 'CHANGE_PROFILE_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCEEDED = 'GET_USER_DATA_SUCCEEDED';
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED';
export const FOLLOWED_ON_USER = 'FOLLOWED_ON_USER';
export const UNFOLLOWED_ON_USER = 'UNFOLLOWED_ON_USER';
export const GET_TWEETS_PROFILE_SUCCEEDED = 'GET_TWEETS_PROFILE_SUCCEEDED';
export const GET_TWEETS_PROFILE_FAILED = 'GET_TWEETS_PROFILE_FAILED';
export const GET_TWEETS_PROFILE = 'GET_TWEETS_PROFILE';
export const ADD_TWEET_TO_STATE = 'ADD_TWEET_TO_STATE';

